### ISSUE TITLE
Add Developer

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.visualstudio.code#109]
![Captura de tela de 2019-09-18 08-10-33](https://user-images.githubusercontent.com/26097419/65143630-d8d6ab80-d9eb-11e9-8c91-58bc48788dd7.png)
dd

**Comment by eszlari** [comment]
https://github.com/flathub/com.visualstudio.code/commit/34d069c9599fc42406d831f7fe020b1d9d1683a6
