### ISSUE TITLE
`code` command is not accessible from command line

### ISSUE THREAD

**Issue by liamdawson** [flathub/com.visualstudio.code#11]
I would like to be able to use `code` as an executable from the command line much as I can with an `rpm` install (such as `code project_folder` to open an instance of VS Code on that folder).

**Comment by TingPing** [comment]
Recent versions of `flatpak` add exports for executables in `~/.local/share/flatpak/exports/bin` and `/var/lib/flatpak/exports/bin` and a `com.visualstudio.code` will be there which you can either use directly or add a `code` alias in your shell to it.

**Comment by nedrichards** [comment]
Yeah, anything more here is an issue for the flatpak command itself.

**Comment by LiamPerson** [comment]
#303 Related
