### ISSUE TITLE
scriptcs extension not finding mono command

### ISSUE THREAD

**Issue by SeattleSlough** [flathub/com.visualstudio.code#127]
I'm running a mac with Catalina.  I've installed scriptcs via brew and Mono from the publisher's site.

When I click the 'play' button for a .cs file I get the following error:
/usr/local/bin/scriptcs: line 2: mono: command not found

Mono is located here: 
/Library/Frameworks/Mono.framework/Versions/Current/bin//mono

scriptcs is located here:
/usr/local/Cellar/scriptcs

Mono version: 6.4.0.198
scriptcs version: 0.17.1

**Comment by eszlari** [comment]
This repo is for the **Linux** flatpak verson of VScode!

If you are running Mac, report your bug to:
https://github.com/microsoft/vscode/issues
