### ISSUE TITLE
Improve icon resolutions available

### ISSUE THREAD

**Issue by nedrichards** [flathub/com.visualstudio.code#13]
The remote icon in the appdata needs 64x64 and 128x128px icons to show up in GNOME Software properly, or we could just import the proper icon since we're now much more OK with the trademark implications.

**Comment by jgarciao** [comment]
When you update the icons, can you please use the blue one? The current one (brown) was introduced in version 1.17 but people complained and they went back to blue in version 1.18. More info [here](https://code.visualstudio.com/blogs/2017/10/24/theicon)

![code](https://user-images.githubusercontent.com/66894/35516274-a74fd78c-050b-11e8-9e6e-b104c06dd9bc.png)

**Comment by nedrichards** [comment]
Yeah, I know - when we had a policy that we could only use remote icons there wasn't a blue iteration available and 'an icon' was better than 'no icon'.

**Comment by nedrichards** [comment]
@jgarciao if you feel strongly about it in the short term I'd be happy to merge a PR, otherwise I'll get to it at some point.

**Comment by jgarciao** [comment]
I saw in the [build file](https://github.com/flathub/com.visualstudio.code/blob/6fbad98ec7da76778dccac52fb66c9fcbe4ccaf2/com.visualstudio.code.json#L103) that the icon is copied from the original code.tar.gz to export/share/icons/hicolor/512x512/.  Maybe they changed it but now the icon provided is 1024x1024

Is is possible to use imagemagick during the build to create a resized image from the original?
```
 {
        "type": "script",
        "dest-filename": "apply_extra",
        "commands": [
            "tar -xf code.tar.gz",
            "rm -f code.tar.gz",
            "mv VSCode-linux-* vscode",
	    "convert vscode/resources/app/resources/linux/code.png -background none -resize 128 vscode/resources/app/resources/linux/code-128.png
            "install -Dm644 vscode/resources/app/resources/linux/code.png export/share/icons/hicolor/512x512/apps/com.visualstudio.code.png",
  	    "install -Dm644 vscode/resources/app/resources/linux/code-128.png export/share/icons/hicolor/128x128/apps/com.visualstudio.code.png",
            "install -Dm644 /app/share/applications/code.desktop export/share/applications/com.visualstudio.code.desktop"
        ]
},

```

Just my 2 cents. I don't have a lot of time to try this now. I can wait ...

**Comment by nedrichards** [comment]
@jgarciao that's the extra-data script, which is applied on their tarball when it's downloaded by the end user - the assets from that script aren't present on flathub or in the build system - which is why we were using appstream remote icon support from the appdata.

**Comment by nedrichards** [comment]
With the remote icon removed and with icons in the package, this should be fixed.
