### ISSUE TITLE
Support for the vscode-java extension

### ISSUE THREAD

**Issue by ghisvail** [flathub/com.visualstudio.code#14]
I currently run a Debian machine with `vscode` installed both as `.deb` and via `flatpak`. I have also got the default JDK package installed, which satisfies the requirements for running the `vscode-java` extension.

The `flatpak` version keeps throwing an error with the following message "The JAVA_HOME environment variable points to a missing folder", whereas the packaged version does not. I suspect the `flatpak` confinement prevents `vscode` from finding the JDK installed on the system.

Would there be an easy way to expose JAVA_HOME to `vscode` without having to bundle the JDK and / or the `vscode-java` extension in the `flatpak`?

**Comment by Barthalion** [comment]
There is [openjdk9](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk9) extension available. Can you try installing it and testing if `flatpak run --env=JAVA_HOME=/usr/lib/sdk/openjdk9  com.visualstudio.code` changes anything?

**Comment by ghisvail** [comment]
@Barthalion Your suggestion got me past the `JAVA_HOME` issue. Now I am getting further messages:
```
Error: Java-based Language Server requires Java 8 or higher (using /usr/lib/sdk/openjdk9/bin/java)
Warn: Classpath is incomplete. Only syntax errors will be reported
```
The error is from `Spring Boot Java Support`, the warning from `Language Support for Java by Redhat`.

**Comment by ghisvail** [comment]
Apart from that, it looks like the language server is now running.

**Comment by Barthalion** [comment]
I never did anything with Java, so correct me if I came to wrong conclusions from googling. Apparently using Java 9 is [not quite supported](https://github.com/redhat-developer/vscode-java/issues/173) by upstream of the plugin, so I guess nothing to do about this. (IIRC we aren't providing openjdk8 as it was problematic on arm and aarch64 architectures).

The latter could be ignored, according to [this upstream ticket](https://github.com/redhat-developer/vscode-java/issues/107):

> This warning is displayed when you open a single java file, because at that point, no classpath can be configured thus no information on types other than the default JDK can be provided. In that case, only syntax errors are reported. Else you'd get compilation errors all over the place. Javadoc and Navigation to classes from the JDK are available.

So if these two things are true, I will just push a change that will define `JAVA_HOME` by default.

**Comment by nedrichards** [comment]
I'm happy to add the environment variable etc. that would let this work easily as an optional install but relucatant to make this forced for everyone. Is there any other settings required?

**Comment by ghisvail** [comment]
Closing as the only appropriate solution is to tweak the settings per extension to point them towards your openjdk extension of choice.
