### ISSUE TITLE
Enable all SDK extensions

### ISSUE THREAD

**Issue by FakeShemp** [flathub/com.visualstudio.code#143]
Would it be possible to add something like `FLATPAK_ENABLE_SDK=ALL` to enable all installed SDKs on your system?

**Comment by barthalion** [comment]
I don't think I understand. You can run app only on one runtime/SDK.

**Comment by FakeShemp** [comment]
I mean enable all SDK extensions, like in the documentation.

It states you can do `FLATPAK_ENABLE_SDK=dotnet,golang flatpak run com.visualstudio.code` so I'm sure you can enable several. But if you want to enable all extensions you have, a shorthand would be nice to have.

**Comment by barthalion** [comment]
Is that variable magically handled by the app? In general SDK extensions are enabled automatically as long as pplication uses SDK as its runtime and extensions are installed. I've never seen FLATPAK_ENABLE_SDK variable but maybe I just missed it somehow.

**Comment by FakeShemp** [comment]
This seem to magically be handled by the [launch script](https://github.com/flathub/com.visualstudio.code/blob/master/code.sh) of this app, yes. I think you want to avoid using these SDK extensions as runtimes since that would cause a lot of bloat. vscode handles so many languages.

**Comment by barthalion** [comment]
Yeah, sounds easy then. I'd even consider doing so by default but I will leave the decision to @eszlari.

**Comment by eszlari** [comment]
Feel free to open a PR for `FLATPAK_ENABLE_SDK=ALL`, I would happily merge it.

**Comment by eszlari** [comment]
Maybe that variable should be renamed to `FLATPAK_ENABLE_SDK_EXT`.
