### ISSUE TITLE
Missing url handler registration

### ISSUE THREAD

**Issue by l-lotz** [flathub/com.visualstudio.code#149]
I wanted to use Live share, but the login is not possible, as firefox does not know how to handle the "code-oss" protocol (the URL starts with "code-oss://ms-vsliveshare.vsliveshare/..."). In the zoom flatpak I saw that they have a mimetype in the desktop file which seemt to enable the protocol for zoom:
`MimeType=x-scheme-handler/zoommtg;`
So I would assume that adding
`MimeType=x-scheme-handler/code-oss;`
could fix this, but I have not tried it.

**Comment by jurf** [comment]
This still stands; the missing desktop file looks like this:

```desktop
[Desktop Entry]
Name=Visual Studio Code - URL Handler
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --no-sandbox --open-url %U
Icon=com.visualstudio.code
Type=Application
NoDisplay=true
StartupNotify=true
Categories=Utility;TextEditor;Development;IDE;
MimeType=x-scheme-handler/vscode;
Keywords=vscode;
```

I have not yet managed to get it to work with the Flatpak edition, but I ran out of time, so I’m leaving it here for now.

**Comment by jurf** [comment]
A workaround, for now, is to run the ‘Developer: Open URL’ command.
