### ISSUE TITLE
VScode freezes on launch on silveblue rawhide

### ISSUE THREAD

**Issue by ellietheoracle** [flathub/com.visualstudio.code#155]
interestingly, the menu items at the top, File, Edit, Selection, View, etc are functional, at least to the degree that you can click on them, none of the actions seem to work.

**Comment by eszlari** [comment]
I can not reproduce this on Kubuntu 19.10, must be a silverblue specific problem.

**Comment by ellietheoracle** [comment]
is there tests or other information i could provide to help diagnose the issue? another note is that the OSS fork of visual studio also on flathub works fine.

**Comment by eszlari** [comment]
Error messages on the command line?
Does the binary from https://code.visualstudio.com/#alt-downloads work, when you exract the tar archive in your /home?

**Comment by ellietheoracle** [comment]
no error messages

`~> flatpak run com.visualstudio.code`
`~>`

and the tar version works fine

**Comment by eszlari** [comment]
journalctl ?

**Comment by ellietheoracle** [comment]
couldn't find anything there either

**Comment by eszlari** [comment]
`flatpak run com.visualstudio.code --disable-gpu` ?

**Comment by ellietheoracle** [comment]
yeah that worked

**Comment by eszlari** [comment]
What's your GPU driver?

If it's Mesa, report at https://gitlab.freedesktop.org/mesa/mesa/-/issues and when it's fixed, the freedesktop runtime needs to be updated: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/

**Comment by ellietheoracle** [comment]
ok so i removed the mesa drivers and now performance is.. intermittent sometimes it will load a document and work ok, but other times it just freezes again

**Comment by ellietheoracle** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/2089 looks like this could be the issue already?

**Comment by eszlari** [comment]
> ok so i removed the mesa drivers

How? What is your GPU actually?

> https://gitlab.freedesktop.org/mesa/mesa/-/issues/2089 looks like this could be the issue already?

That bug report has nothing to do with VSCode.

**Comment by ellietheoracle** [comment]
oh you're right, my bad.
i just have intel integrated graphics, and i had 32bit mesa drivers installed for some other app and after i removed those is worked better but still not reliably.
