### ISSUE TITLE
Podman use

### ISSUE THREAD

**Issue by giomke** [flathub/com.visualstudio.code#189]
Hello guys.
My goal is to use remote container extension. How to install podman inside sandbox or it is possible to  reach out from sandbox to communicate with Podman binary

**Comment by HarryMichal** [comment]
There is already #55 somewhat discussing this. But I'll also answer here. As far as I know, it's not possible to use Podman with the flatpaked VSCode by default. The main reason is that VSCode itself is not aware of being in a flatpak and there is no podman binary in its environment. But you can bypass it. Steps:

1. Create a file with a name of your choice (I called mine simply `podman`) and write into it:
```sh
#!/bin/sh

exec flatpak-spawn --host podman "$@"
```
2. Put the file somewhere, where it can be accessed from the flatpak (I put mine in the root of my home folder).
3. Open VSCode
4. Go to Settings of the Remote-Container extension
5. Set `Docker Path` to the absolute path to the podman wrapper you created

If the extension still complains about missing Docker, I recommend checking if the flatpak can really see the file.

**Comment by giomke** [comment]
> There is already #55 somewhat discussing this. But I'll also answer here. As far as I know, it's not possible to use Podman with the flatpaked VSCode by default. The main reason is that VSCode itself is not aware of being in a flatpak and there is no podman binary in its environment. But you can bypass it. Steps:
> 
>     1. Create a file with a name of your choice (I called mine simply `podman`) and write into it:
> 
> 
> ```shell
> #!/bin/sh
> 
> exec flatpak-spawn --host podman "$@"
> ```
> 
>     1. Put the file somewhere, where it can be accessed from the flatpak (I put mine in the root of my home folder).
> 
>     2. Open VSCode
> 
>     3. Go to Settings of the Remote-Container extension
> 
>     4. Set `Docker Path` to the absolute path to the podman wrapper you created
> 
> 
> If the extension still complains about missing Docker, I recommend checking if the flatpak can really see the file.

Thank you very much. It worked but still, I have various errors. I decided to work without a flatpak. By the way, very interesting tips thank you for sharing
