### ISSUE TITLE
Update fails with error "apply_extra script failed"

### ISSUE THREAD

**Issue by michael-rapp** [flathub/com.visualstudio.code#202]
I am unable to update Visual Studio Code by running `$ flatpak update`. It is prompted that a new version is available, which will be downloaded properly, but afterwards the installation fails with the following error message:
```
Error: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
Updates complete.
error: There were one or more errors
```
Other packages can be updated as usual.

Retrieving more information about the currently installed package via `$ flatpak info com.visualstudio.code` results in the following output:
```
Visual Studio Code - Visual Studio Code. Code editing. Redefined.

           ID: com.visualstudio.code
          Ref: app/com.visualstudio.code/x86_64/stable
         Arch: x86_64
       Branch: stable
      Version: 1.52.1-1608136922
      License: LicenseRef-proprietary=https://code.visualstudio.com/license
       Origin: flathub
   Collection: org.flathub.Stable
 Installation: system
    Installed: 2,3 MB
      Runtime: org.freedesktop.Sdk/x86_64/20.08
          Sdk: org.freedesktop.Sdk/x86_64/20.08

Active commit: 4aaff364b0a3f5a58cb2c5171a83a2fbe4fc1ecb72af4f04dab5ff18426c6d2a
Latest commit: 276f74631dab0fc90497f52f319343506016c393a7ef23a70d3f75613ef20dab
       Parent: 7c25c84bdde983beb16a1bf09bc1826ee317404cd802480c4cf0e1007c0f97a9
      Subject: enable automerge-flathubbot-prs (c25c785e)
         Date: 2020-12-19 22:32:01 +0000
```
My system is running Arch Linux with Flatpak version 1.10.1.

**Comment by michael-rapp** [comment]
I tried reinstalling the application with `$ flatpak install --reinstall com.visualstudio.code`, which resulted in the exact same error and as a result my installation was gone. Today I tried to install again using $ flatpak install com.visualstudio.code` and it worked. I don't know if there was a new release in the meantime, but everything seems to be back to normal now.

**Comment by awptechnologies** [comment]
I have this error as well. Started happening last night
