### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by nicolascochin** [flathub/com.visualstudio.code#247]
Hi, 

I'm sorry if my question has been answered before. I googled it, but I didn't find any answer. 
I'm wondering why this flatpak is not updated any more? 
The actual flatpak's version is 1.57.1 and the actual vscode's version is 1.59.1. 
From memory, this flatpak has always been updated quite the same time as vscode. 
Thank you

**Comment by hunger** [comment]
Does #251 fix the issue?

It would rock to get the newer versions at some point:-)

The VScodium and Code - OSS flatpaks are at 1.60.2 for a while now, but unfortunately the remote plugin does not work with those. Maybe you can share some ideas between the different VSCode packages?
