### ISSUE TITLE
Integrated terminal cannot find system executables

### ISSUE THREAD

**Issue by mlewis-everley** [flathub/com.visualstudio.code#25]
Hi,

I originally reported this here: https://github.com/Microsoft/vscode/issues/44646

But it appears to be an issue with the Flatpack version of VS Code. It almost appears that the flatpack version is running the integrated terminal in a chrooted environment.

**Comment by TingPing** [comment]
Flatpaks are sandboxed, they cannot directly run host binaries.

**Comment by alexbrrsclnt** [comment]
So there is no solution to this problem? What is the advantage then of the flatpak version over the original .deb? More security, etc, but not the same funcionality

**Comment by mlewis-everley** [comment]
Have to admit I kind of agree with @alexbrrsclnt. There are issues that go beyond just the terminal that I suspect are also related to the sandbox, for example:

- Composer module does not work (cannot find executable).
- Integrated PHP reports regular errors (due to executable path).
- Trying to run tasks, such as transpiling SCSS/Less (as outlined in the official docs: https://code.visualstudio.com/Docs/languages/CSS) causes errors.

If you are saying these issues cannot be resolved, is there really a good reason to include this package?

**Comment by TingPing** [comment]
I don't use VSCode but for example I use Atom and almost every language from Python, Ruby, Node, support installing into private directories so I can just `pip3 install --user some-tool`. Now the specific Flatpak needs to be configured for that but this isn't hard and yes you will hit limitations where you need native dependencies in which more complicated solutions must be done but it isn't *useless* it is just limited.

**Comment by nedrichards** [comment]
Yeah - there are strengths and weakness' to this approach but it's the one that we have and it's not going to change.  If you need something that's *not* in a container, then you shouldn't be looking at Flatpak or Flathub to give it to you I'm afraid.

**Comment by JulienRobitaille** [comment]
I know that this issue is old, but for anyone looking on how to make zsh (or your favourite shell) works:
In `settings.json`:
```json
{
    "terminal.integrated.shell.linux": "flatpak-spawn",
    "terminal.integrated.shellArgs.linux": ["--host", "zsh"]
}
```
For another shell just change the  "zsh" for the right binary.

The environment variable $TERM also needs to be set to your favourite running terminal type (probably xterm-256color, xterm or xterm-kitty).
You can set this one in  .zshrc like so:
`export TERM=xterm-256color`


I've used some precious information from: https://github.com/flathub/com.visualstudio.code/issues/39
