### ISSUE TITLE
"com.visualstudio.code.insiders" should become one branch of "com.visualstudio.code".

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [flathub/com.visualstudio.code#256]
"[com.visualstudio.code.insiders](http://github.com/flathub/com.visualstudio.code.insiders)" should be merged with "[com.visualstudio.code](http://github.com/flathub/com.visualstudio.code)" as one branch of "[com.visualstudio.code](http://github.com/flathub/com.visualstudio.code)" so that "[com.visualstudio.code.insiders](https://github.com/flathub/com.visualstudio.code.insiders)" shall be able to be invoked as "[`flatpak run com.visualstudio.code//insiders`](http://github.com/flathub/flathub/issues/1915#issue-734456405)".

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
http://github.com/flathub/com.visualstudio.code.insiders/issues/495

**Comment by fooishbar** [comment]
I don't quite understand your suggestion, since you link to a report suggesting this is not actually possible to implement with Flatpak/Flathub currently.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/flathub/com.visualstudio.code/issues/256#issuecomment-932319586.

Regardless of whether the modification that is proposed by the issue that I have posted the hyperlink to shall be implemented, this package having two package names is very strange, and is not like most other software. Regardless of what Microsoft happens to call its devemopmental version of Visual Stduio Code, this is merely the developmental version of it, and thus should be treated as most others are.

**Comment by fooishbar** [comment]
When this package was first proposed, the suggestion from Flathub developers was that it should be a separate app ID, so it could be installed side-by-side and run separately, reflecting the nature of Insiders builds (extremely fast-moving, sometimes broken).

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/flathub/com.visualstudio.code/issues/256#issuecomment-932329381

Is that not possible for what I have proposed?

**Comment by fooishbar** [comment]
Not to the best of my knowledge ...

**Comment by barthalion** [comment]
It is the way it is by design, because we want both refs to be visible in the menu.
