### ISSUE TITLE
Migrate config from Host to Flatpak

### ISSUE THREAD

**Issue by f0o** [flathub/com.visualstudio.code#265]
Hi,

I'd like to migrate my config (and ideally extensions etc) from my host installation into the Flatpak one to avoid resetup of literally everything.

Any idea where I should place `~/.vscode` ? It didnt seem to pick it up right away

**Comment by mkfrey** [comment]
Somewhere inside of `~/.var/app.visualstudio.code`. Propbably `config/Code`.

**Comment by f0o** [comment]
ok turns out that `~/.config/Code` goes to `~/.var/app/com.visualstudio.code/config/Code` and `~/.vscode` goes to `~/.var/app/com.visualstudio.code/data/vscode` (note the missing `.` in the directory name)
