### ISSUE TITLE
some problem with terminal (is that really critical?)

### ISSUE THREAD

**Issue by dcykhub** [flathub/com.visualstudio.code#273]
**After I open a Terminal inside of VSCode, it gives me this error:**
```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[evghenii@fedora ~]$
```
I'm using Fedora Silverblue 35.

Here is my config file:
```
{
    "window.titleBarStyle": "custom",
    "terminal.integrated.defaultProfile.linux": "bash",
    "terminal.integrated.profiles.linux": {
        "bash": {
          "path": "/usr/bin/flatpak-spawn",
          "args": ["--host", "--env=TERM=xterm-256color", "bash"]
        }
    }
}
```
I don't know if that is actually critical, but it disturbs me.

**Comment by CleoMenezes** [comment]
It is calling bash twice and one of them is no longer used I believe.
Remove `"terminal.integrated.defaultProfile.linux": "bash`" and see if it works.

**Comment by dcykhub** [comment]
okay, I don't know why, it now doesn't show it
