### ISSUE TITLE
flatpak list reports an outdated version number

### ISSUE THREAD

**Issue by hferreiro** [flathub/com.visualstudio.code#276]
```
$ flatpak list | rg code
Visual Studio Code	com.visualstudio.code	1.60.2	stable	flathub	user
```

I guess the reason is that the file [`com.visualstudio.code.metainfo.xml`](https://github.com/flathub/com.visualstudio.code/blob/master/com.visualstudio.code.metainfo.xml#L24) is missing the latest releases.

**Comment by niklasengvall** [comment]
I would appreciate a newer flatpak version of vs code, many thanks in forward.
