### ISSUE TITLE
"code" command isn't working 

### ISSUE THREAD

**Issue by javidizadi** [flathub/com.visualstudio.code#303]
"code" binary isn't added to System PATH and I don't have permission to run it as a normal user.

**Comment by different55** [comment]
That's not how applications are run with flatpak. Flatpak apps are run with `flatpak run <Application ID>` so for VS Code, that'd be `flatpak run com.visualstudio.code`.

**Comment by izakdvlpr** [comment]
I solved this problem by typing the following alias in my terminal:  `alias code="flatpak run com.visualstudio.code"`
