### ISSUE TITLE
Version updates not fast enough

### ISSUE THREAD

**Issue by jacokok** [flathub/com.visualstudio.code#321]
Hi currently my main issue with the flatpak version of vscode is that it takes too long to get approved.
It seems like the flathubbot prs are looking good and was wondering about viability of enabling the auto merge pr for flathubbot.

```json
{
  "automerge-flathubbot-prs": true
}
```

**Comment by JoshStrobl** [comment]
1.68 was released last month. If folks are not able to review PRs in a timely matter at this moment in time (understandable, everyone is a volunteer, it's summer / vacation time for many, etc.) then automerging flathub bot PRs until there is confidence that it is no longer necessary may be advantageous. I would be curious to hear the reasons it ended up getting disabled as well :)

Thoughts @nedrichards ?

**Comment by dhollinger** [comment]
I'm in agreement with @JoshStrobl, if the updates aren't in near lock-step with the APT/YUM/Arch repos, then it makes the flatpak largely pointless in comparison to those methods of install

**Comment by JoshStrobl** [comment]
Gonna be _that_ guy and ping someone else as well that has recently made commits. @barthalion

**Comment by barthalion** [comment]
I disabled automatic merges as at least on one occasion it broke the app completely. There is no active maintainer here, and as I don't use VSCode at all, I'm not qualified to review and merge everything that is going on here. Neither I have space on my plate to handle this.

I can either invite one of you to collaborators, so you can handle testing and merges without my involvement, or just mention me at PRs you consider ready.

**Comment by JoshStrobl** [comment]
@barthalion Honestly I am not that familiar with packaging for flatpak (I have experience with other packaging formats), but I would be open to learning and helping to maintain it. I will test out the PRs and ping on the PRs that are validated to work.

**Comment by narniano** [comment]
IDK how this works, but every other packaging system is update but flatpak.

**Comment by jacokok** [comment]
I am closing this as believe @barthalion answered my original question.

While we could automerge flatbot requests and get faster releases he is advising us that it broke the app before.
It all comes down to us as the community to step up and become collaborators.

For now we can mention @barthalion after we tested flatbot merge requests to get faster releases.
