### ISSUE TITLE
Are there any wiki with instructions somewhere?

### ISSUE THREAD

**Issue by jcnils** [flathub/com.visualstudio.code#323]
I am quite new to flatpak
When I first installed Visual Studio from Flatpak it was mostly a text editor that doesn't integrate with anything. 

Some things I needed I found around the web / issues page, but still there are much missing.

For example:

- None of the language integration - I discovered later here in the issues page that I can make it work partially [with SDK](https://github.com/flathub/com.visualstudio.code/issues/138)
- Integrated terminal configuration - Same as before, found on the issue page how to set the profiles.
- Run from terminal with "code" - aliases.
Pretty much Frankenstein's monster now.

Flatseal also helped with a few things.

On the other hand, as long as I am developing inside docker containers/remote, I haven't had many problems. 

Most flatpak packages I tried worked fine out of the box, some of them had a wiki for those common issues that made fixing things easier. It would be nice if there was a wiki or something like that here.

**Comment by nikodunk** [comment]
I dismissed the flatpak-warning the first time I started the integrated terminal, and then also had to go digging.

Maybe we could add a link to https://github.com/flathub/com.visualstudio.code/blob/master/flatpak-warning.txt as a README.md of the Flathub VSCode repo so that it appears under https://github.com/flathub/com.visualstudio.code?

**Comment by barthalion** [comment]
Not sure I get the point, though. Is `flatpak-warning.txt` displayed only once?

**Comment by jcnils** [comment]
To be fair, I don't remember that warning appearing at all, I found an issue here with its description and followed it. 

I think the README idea is great. The contents you mentioned might have what most people will need, I add the information from the warning straight there to make it easier to find.

But I still think it would be a good idea to have a proper FAQ/Wiki here, but I don't know if the maintainers have permissions for that. Maybe github pages.

Because there are plenty of posts on the issues pages of people struggling with the sandbox access to things they need to work (extensions, integrations, etc).

**Comment by jcnils** [comment]
Probably, It is better than nothing, but it might get chaotic in the long run when the FAQ becomes bigger.

I added some stuff in a PR to your repo yesterday, so everything is in the readme.

**Comment by nikodunk** [comment]
Ah yes didn't see your PR. Great suggestions! Merged to my PR.

@barthalion or @jcnils sorry to bother ya but could we get a review for https://github.com/flathub/com.visualstudio.code/pull/324 please? I feel like it would help a lot of users out a bunch when switching to Flatpak VSCode, and quash various recurring issues that get opened although they're already documented/solved in this hard-to-find .txt file.
