### ISSUE TITLE
Forward ssh-agent socket into the sandbox

### ISSUE THREAD

**Issue by mzabaluev** [flathub/com.visualstudio.code#33]
To facilitate working with git over ssh, it would be nice if the sandbox had access to the ssh-agent socket from the user session. flatpak/flatpak#1438 says this is feasible with manual override options of `flatpak run`, but it would be great if the app had it out of the box.

**Comment by JeffLabonte** [comment]
I agree with @mzabaluev, that would great to be able to do so out of the box!

**Comment by mzabaluev** [comment]
For an individual installation, the problem can be solved persistently with
`flatpak override --socket=ssh-auth com.visualstudio.code`.
So only "out of the box" part is missing.

**Comment by nedrichards** [comment]
Should be fixed by https://github.com/flathub/com.visualstudio.code/commit/4d6ea9a952b34c2956510885a2fcb67e4d97a1f3
