### ISSUE TITLE
FLATPAK_ENABLE_SDK_EXT not working on Fedora Silverblue

### ISSUE THREAD

**Issue by j0hax** [flathub/com.visualstudio.code#344]
Hello, I am trying to get Golang working on my fresh Fedora Silverblue 36 install.

Running `flatpak install flathub org.freedesktop.Sdk.Extension.golang`  before running results in an error:

```console
$ FLATPAK_ENABLE_SDK_EXT=golang flatpak run com.visualstudio.code
flatpak-vscode: Requested SDK extension "golang" is not installed
```

This doesn't appear to affect Go specifically, the same error occurs when trying the `node12` SDK.

**Comment by CleoMenezesJr** [comment]
I don't know exactly why in documentation says to do this when the change does not seem to remain. With Neovim, I use `flatpak override --user --env=FLATPAK_ENABLE_SDK_EXT=rust-stable,node16 io.neovim.nvim` for example. Or even simpler with Flatseal, go to the Environment > Variables and add `FLATPAK_ENABLE_SDK_EXT=rust-stable,node16`, but in this case the Golang.

**Comment by j0hax** [comment]
Thanks for the pointer. While your solution should work on most distributions, this doesn't seem to be the case with Silverblue, as it mounts `/usr` a read-only. As a result I have no `/usr/lib/sdk` directory on my system, which [appears to be the directory](https://github.com/flathub/com.visualstudio.code/blob/25f9c9033ccaff29bef83dc9f80a1b869580009c/code.sh#L43) used for SDK Extensions.

I'll close this issue as it appears to be more of an Issue with Flatpaks on Fedora Silverblue as a whole instead of just VS Code.

**Comment by CleoMenezesJr** [comment]
> 

I'm using Silverblue too. I don't quite understand what it has to do if it is mounted or not in `/usr` whether SDK is flatpak.

Furthermore, I just do it in the Neovim (flatpak):
![image](https://user-images.githubusercontent.com/54215258/190009209-f0aa9633-c1b4-4a76-b203-9cfc5e8ae3a4.png)

**Comment by j0hax** [comment]
> I don't quite understand what it has to do if it is mounted or not in `/usr` whether SDK is installed as Flatpak.

The [script](https://github.com/flathub/com.visualstudio.code/blob/55630ba68eb08f2b148238ecd6d44f4b2f94838e/code.sh#L43) to start the VS Code Flatpak references `/usr/lib/sdk/`, which doesn't exist in my Silverblue installation, even with specific SDKs installed.

**Comment by nicocti** [comment]
Same here, I tried both golang and rust-stable 23.08 channels, but only 22.08 worked :/
Did you upgrade your SDKs while still running Silverblue ?
