### ISSUE TITLE
podman tool doesnt work anymore after upgrade to vscode 1.17.2

### ISSUE THREAD

**Issue by sennierer** [flathub/com.visualstudio.code#351]
after upgrading to the latest vscode version I dont get the podman-remote command in vscode anymore and vscode is complaining that I need to install docker.

**Comment by gasinvein** [comment]
Ah, I see, this (proprietary) VSCode flatpak has updated the runtime to 22.08 a0ca706e66cc852bbe49186e80d5c57886c8ab3a

**Comment by gasinvein** [comment]
I've submitted the podman tool build with SDK 22.08; when it lands on flathub, install `com.visualstudio.code.tool.podman//22.08`

**Comment by sennierer** [comment]
great, thx!

**Comment by sennierer** [comment]
after installing the new version its working as intended. Thanks again!
