### ISSUE TITLE
Can't use Dev Containers extension

### ISSUE THREAD

**Issue by DeepDoge** [flathub/com.visualstudio.code#377]
I use [Dev Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) to have a different Docker container per project.
But can't make it work with Flatpak vscode.

I gave it access to `/run/docker.sock`, and I can also use, `docker` on the terminal.
But when I try to open the the folder in container, it says "Docker is required".

Also just realized that official Docker extension also not working.
It says "Failed to connect." also gives this output:
```
Failed to set up event listener: spawn docker ENOENT
```

EDIT: Oh I see, i was using flatpak-spawn terminal, i need `docker` in the container's terminal.

**Comment by DeepDoge** [comment]
Solution: https://github.com/flathub/com.visualstudio.code/issues/55#issuecomment-1409226145

**Comment by asule90** [comment]
i added those setting, but this error persists everytime i run `rebuild and reopen in container`:

```json
{
    "message": "Command failed: /app/extra/vscode/code --ms-enable-electron-run-as-node /home/<username>/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js read-configuration --docker-path /run/host/usr/bin/docker --docker-compose-path /run/host/usr/bin/docker-compose --workspace-folder /home/<username>/project --log-level debug --log-format json --config /home/<username>/project/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true",
    "code": 1
}
```

can you help me?

**Comment by DeepDoge** [comment]
@asule90 have you mounted/exposed `/run/docker.sock` to your flatpak? if you already did i really don't know what might be the cause of the issue.
