### ISSUE TITLE
Update to 1.76.0

### ISSUE THREAD

**Issue by BoltsJ** [flathub/com.visualstudio.code#385]
https://code.visualstudio.com/updates/v1_76

**Comment by mrBen** [comment]
1.76.1 is out since

**Comment by xduugu** [comment]
Any change to get https://github.com/flathub/com.visualstudio.code/pull/389 merged?
Who has push-access to this repository? Maybe @TingPing or @barthalion?
Thanks a lot!

**Comment by xduugu** [comment]
Thanks, @barthalion!
I think this issue can be closed now, but it is still unclear how future updates should be handled.
