### ISSUE TITLE
Host runtime binaries

### ISSUE THREAD

**Issue by anfrantic** [flathub/com.visualstudio.code#4]
Is there some way to access system binaries like /usr/bin/go inside sandbox? Many plugins do need system binaries to work properly.

**Comment by TingPing** [comment]
No, Flatpaks are sandboxed and while they can in some form see the host they cannot reasonably be expected to run executables or use libraries from it.

The best solution for `go` specifically would probably be to add it to the package.

**Comment by anfrantic** [comment]
ok, thanks =)

**Comment by redbaron** [comment]
@TingPing , @anfrantic , there is https://github.com/flathub/com.visualstudio.code/blob/31ad9c6af581dbda712729c201e77e4da62cdb6e/com.visualstudio.code.json#L17 which suggests that vscode is running with host filesystem view, therefore any runtime  installed is available to vscode

**Comment by TingPing** [comment]
@redbaron It can view everything, it can't use everything. `/usr` and friends are provided by Flatpak, host `/usr` is mounted in `/run/host/usr` and executables and libraries aren't useful anyway.

**Comment by redbaron** [comment]
well, in my case go is in ~/opt/go and is self contained :)

**Comment by TingPing** [comment]
Maybe, but its a bad habit to consider anything there useful, certainly not safe to configure the IDE to look on the host for binaries by defualt.

**Comment by anfrantic** [comment]
@TingPing most vscode plugins rely on host binaries, i think it's pointless to use fully isolated IDE at all, 'couse it just becomes a fancy text editor with no integration
