### ISSUE TITLE
Bundled CMake version is too old, but using system CMake not possible

### ISSUE THREAD

**Issue by akors** [flathub/com.visualstudio.code#41]
Hi, I was trying to use the FlatPak version of Visual Studio code, and for the most part it works fine.

I was trying to use CMake with the following extension: https://github.com/vector-of-bool/vscode-cmake-tools

This failed because my project requires CMake > 3.11, but the CMake version packaged in the `org.freedesktop.Sdk/x86_64/1.6` SDK is pretty old, namely 3.7.2.

I tried to use the system CMake, but that doesn't work because flatpak mounts the runtimes over the system `/usr/bin`, even when running with `--filesystem=host`.

I think there should be a better way for integration for system tools with VSCode.

**Comment by nedrichards** [comment]
I agree with you, but that's more of an issue for https://github.com/flatpak/flatpak than it is here. Someone will possibly look and think about a general solution there!

**Comment by akors** [comment]
@nedrichards could you please specify what kind of an issue of flatpak that is and which features you are missing?

I'm not a FlatPak expert, but GNOME builder seems to be able to do this just fine. I can open terminals and access all my host files, including my system CMake.

Considering gnome-builder is also an IDE just like VS Code, you might wanna take a look at how they are building their flatpaks: https://gitlab.gnome.org/GNOME/gnome-builder/blob/gnome-builder-3-28/build-aux/flatpak/org.gnome.Builder.json

**Comment by nedrichards** [comment]
GNOME Builder is custom coded to work inside a container and in partnership with a host system, spawning new containers where necessary and using host command etc. to get an experience that good takes real work and it'd have to be upstream in VS Code. I'd be delighted to help package it where available but the point of this version is to 'take the bits from microsoft and use them without changes'.

Certainly it's possible to do a lot better than we do here via extensions etc. but it'd need contributions from someone who isn't me.

As an aside, this is likely to get mitigated real soon now by switching to the 18.08 version of the freedesktop sdk. That version will come with cmake 3.12: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/18.08/elements/base/cmake.bst

**Comment by akors** [comment]
OK, I see the issue now.

> As an aside, this is likely to get mitigated real soon now by switching to the 18.08 version of the freedesktop sdk

That might fix my use case, but i'm worried that interacting with the host system will always be somewhat problematic.

Thanks for your work!
