### ISSUE TITLE
fail to access local sdk configuration

### ISSUE THREAD

**Issue by chengjk84** [flathub/com.visualstudio.code#42]
i have multiple sdk install the machine at user level, load through PATH at zshrc file... 
eg. flutter sdk at ~/.flutter-sdk, and android sdk at ~/.android-sdk

everything work fine on rpm installed version of vscode... however, the flatpak version of vscode fail to load those defined sdk... is this the problem of vscode extension or problem of flatpak app structure???

**Comment by TingPing** [comment]
It can read from `~` just fine, so maybe its expecting some other tool or libraries.
