### ISSUE TITLE
Confusion Regarding Installation Instructions for Linux Newbies

### ISSUE THREAD

**Issue by rossanodr** [flathub/com.visualstudio.code#435]
The instructions are not clear for the installation. I am new to the Linux world and quite confused.

"Execute commands in the host system.
To execute commands on the host system, run inside the sandbox:

$ flatpak-spawn --host <COMMAND>

or

$ host-spawn <COMMAND>

Most users seem to report a better experience with host-spawn."

Where should I enter these commands?

**Comment by bilelmoussaoui** [comment]
In the terminal

**Comment by bilelmoussaoui** [comment]
VSCode's terminal to be precise
