### ISSUE TITLE
Is there a way to access system wide installed compilers, includes and libs?

### ISSUE THREAD

**Issue by brcha** [flathub/com.visualstudio.code#50]
I use VSCode as an IDE mostly for C++, LaTeX and Rust. In the current form (where it hides system's /usr) it is completely unusable for me (except for Rust which is installed in my home dir). I've noticed that system /usr is mounted as /var/run/host/usr, so I'm wondering if there is a way to use binaries, include files and libs from there or that's not possible? I do realize that would be slightly breaking the sandbox, but those files are read-only anyway.

**Comment by TingPing** [comment]
> . I've noticed that system /usr is mounted as /var/run/host/usr, so I'm wondering if there is a way to use binaries, include files and libs from there or that's not possible?

In general no.

There are plans to package more tools inside of Flatpak but it just needs to be done. You can launch host tools with `flatpak-spawn --host ...` also.

**Comment by MightyCreak** [comment]
Hi!
I need some help understanding flatpak.

I added this command line:
```flatpak override --user --filesystem=host com.visualstudio.code```
From what I understand, this command should allow VS Code to "see" all the host. But I still don't have access to the compilers binaries in /usr/bin (even after a restart).

Why is that?

**Comment by eszlari** [comment]
@MightyCreak
http://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access

**Comment by MightyCreak** [comment]
Well there is this:
> These directories are blacklisted: /lib, /lib32, /lib64, /bin, /sbin, /usr, /boot, /root, /tmp, /etc, /app, /run, /proc, /sys, /dev, /var

But does that mean that we can't add the compilers binaries no matter what?
