### ISSUE TITLE
Dart extension failed to detect KVM

### ISSUE THREAD

**Issue by chengjk84** [flathub/com.visualstudio.code#51]
Anyone facing this problem?

`Failed to launch emulator: emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: /dev/kvm is not found: VT disabled in BIOS or KVM kernel module not loaded`

`› ll /dev/kvm
crw-rw-rw-. 1 root kvm 10, 232 Sep 18 19:00 /dev/kvm`

**Comment by TingPing** [comment]
Does `flatpak run --device=kvm com.visualstudio.code` work?

**Comment by chengjk84** [comment]
yup it work... thanks for the guide...

**Comment by TingPing** [comment]
You can do `flatpak override --user --device=kvm com.visualstudio.code` to make it permanent.
