### ISSUE TITLE
Unable to debug any c++ program using GDB 

### ISSUE THREAD

**Issue by dkgeext** [flathub/com.visualstudio.code#58]
How to reproduce:
1. Open console in Visual Studio Code
2. type: `gdb ./<any_executable>`
3. run program

Output:
```
warning: Error disabling address space randomization: Operation not permitted
warning: Could not trace the inferior process.
Error:
warning: ptrace: Operation not permitted
During startup program exited with code 127.
```
OS: Ubuntu 18.04 (KDE neon)
flatpak version: 1.0.4

**Comment by nedrichards** [comment]
Can you run this with:

> flatpak run --allow=devel com.visualstudio.code

That should remove some of the syscall filtering from the sandbox.

**Comment by dkgeext** [comment]
> Can you run this with:
> 
> > flatpak run --allow=devel com.visualstudio.code
> 
> That should remove some of the syscall filtering from the sandbox.

Yeah it works with the flag.

**Comment by nedrichards** [comment]
Fixed in https://github.com/flathub/com.visualstudio.code/commit/df339ab19d5429d7fcb02ea969c21f2493c75aa2
