### ISSUE TITLE
openocd installed with platformio inside flatpak won't detect any device

### ISSUE THREAD

**Issue by tpimh** [flathub/com.visualstudio.code#59]
I guess flatpak sandbox doesn't provide device access, so programming or debugging with openocd will always fail. Tried with J-LINK and ST-LINK, the result is the same. Is there any easy way how to fix this?

**Comment by nedrichards** [comment]
`flatpak run --device=all com.visualstudio.code`

should expose access to all of /dev. it's not something that I'd be comfortable having everywhere but you can run like that if you need it.

**Comment by eszlari** [comment]
> it's not something that I'd be comfortable having everywhere

Does it really make much of a difference with `--filesystem=host` and `--allow=devel`?
