### ISSUE TITLE
python extension does not work properly

### ISSUE THREAD

**Issue by tierpod** [flathub/com.visualstudio.code#6]
Python extension for Visual Studio Code can not install pylint:

```
sh-4.3$ "python" -m pip install -U pylint
You are using pip version 7.1.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
...
Exception:
...
OSError: [Errno 30] Read-only file system: '/usr/lib/python2.7/site-packages/backports.functools_lru_cache-1.4.dist-info'
```

Steps to reproduce:
1. fresh install com.visualstudio.code
2. install python extension
3. open python project, appears notification bar with message "Linter pylint is not installed"
4. click in "Install pylint" button

PS. And how about python3 support?

**Comment by tierpod** [comment]
Fast solution: inside internal vscode terminal (after "sh-4.3$" prompt) run:

```
"python" -m pip install -U pylint --user
"python" -m pip install -U flake8 --user
```

**Comment by nedrichards** [comment]
The runtime has access to python3, so it must be choosing 2.7 by default. Are there any environment variables or similar we can set to make the manual override work?

**Comment by tierpod** [comment]
> The runtime has access to python3

This is what I need. I found this solution: https://code.visualstudio.com/docs/python/environments

Thank you for reply, problems solved.
