### ISSUE TITLE
version mismatch or flathub doesn't sync latest update?

### ISSUE THREAD

**Issue by tennom** [flathub/com.visualstudio.code#66]
It prompts this and 1.30.1 is available.

![visual1](https://user-images.githubusercontent.com/8739460/50460468-70552380-09b1-11e9-9245-0f65baf0464b.png)
When I tried to tun update via flatpak, there is no update available. 

In the About menu, it also seems the old version:

Version: 1.30.0
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:21:33.585Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-42-generic

**Comment by eszlari** [comment]
https://github.com/flathub/com.visualstudio.code/commit/17ad970b60390f5da010f6c8e5d0f27064a61c0f
