### ISSUE TITLE
VS Code not launching

### ISSUE THREAD

**Issue by goncalossilva** [flathub/com.visualstudio.code#68]
Freshly installed on Fedora 29, VS Code is not launching. Tried:
* GUI shortcut
* `flatpak run com.visualstudio.code`
* `flatpak run --command=/app/extra/vscode/code com.visualstudio.code`
* `/var/lib/flatpak/exports/bin/com.visualstudio.code`

The resulting error:
`env: ‘/app/extra/vscode/bin/code’: No such file or directory`

(or `bwrap: execvp /app/extra/vscode/code: No such file or directory` when using the third option above)

How can I get it to run? How can I help debug this?

**Comment by goncalossilva** [comment]
To note, VS Code OSS runs without issues.

**Comment by namannehra** [comment]
Same issue on Elementary OS 5.0 for version 1.30.1
```
$ flatpak run -v com.visualstudio.code
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/naman/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/naman/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/naman/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 3483354482
F: Allocated instance id 2977471248
F: Allowing dri access
F: Allowing host-fs access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/naman/.config/pulse/client.conf': Error opening file /home/naman/.config/pulse/client.conf: No such file or directory
F: Running '/usr/lib/flatpak/flatpak-bwrap --args 31 /usr/lib/flatpak/flatpak-dbus-proxy --args=33'
F: Running '/usr/lib/flatpak/flatpak-bwrap --args 28 code'
env: ‘/app/extra/vscode/bin/code’: No such file or directory
```

**Comment by eszlari** [comment]
fixed in: https://github.com/flathub/com.visualstudio.code/commit/c13ca368e417816c1262d20913c81dfa24c30d25

**Comment by ateebahmed** [comment]
facing this same issue in 1.43 release
before I was able to use it, and right after this update it stopped launching and this
`bwrap: execvp code: No such file or directory`
same error occurs
