### ISSUE TITLE
Relicense metadata and restore the appstream check

### ISSUE THREAD

**Issue by mzabaluev** [flathub/com.visualstudio.code#78]
Commit afbab07478750dccd8bfed0bffe3a00e4c68b8ce removed the appstream check for just one problem: `<metadata_license>` not being one of "content" licenses as required by `appstream-util validate` (list as per [here](https://github.com/hughsie/appstream-glib/blob/5518fc339fa0c508c1c7ab7b5d9c8fa0aaca8c4f/libappstream-glib/as-app-validate.c#L1046)).

It seems a simple matter to change the metadata license to conform. @nedrichards @eszlari you are the only other contributors to the current contents of the `.appdata.xml` file. Would you agree to relicense that file under one of the licenses approved by strict validation in appstream-util?

**Comment by nedrichards** [comment]
Sadly, that's not true. It was forked from https://github.com/microsoft/vscode/blob/master/resources/linux/code.appdata.xml which is under the MIT. Agreed that it's not *great* (and also that we should contribute a bunch of these changes back upstream).
