### ISSUE TITLE
appdata version does not reflect the actual Visual Studio Code version

### ISSUE THREAD

**Issue by mzabaluev** [flathub/com.visualstudio.code#8]
The release information in the `.appdata.xml` file, visible via Flathub application metadata in GNOME Software tool and elsewhere, still lists version 1.18.0, even though commits have been made that update the downloaded installables to 1.19.1.

**Comment by nedrichards** [comment]
Yeah - that's a good point. I'll get that done when I can. If you want to get it done more quickly then feel free to submit a PR and I'll review.

**Comment by nedrichards** [comment]
fixed in #10

**Comment by mzabaluev** [comment]
The version looks correct now, thank you.
