### ISSUE TITLE
Update the base app to Electron 4.x

### ISSUE THREAD

**Issue by mzabaluev** [flathub/com.visualstudio.code#88]
VSCode 1.36 [has been updated][release-notes] to Electron 4.x. Make sure the Electron base app provides the correct version or is at least compatible with the Electron engine bundled into VSCode.

[release-notes]: https://code.visualstudio.com/updates/v1_36#_linux-32bit-support-ends

**Comment by TingPing** [comment]
baseapp is just a bundle of dependencies it doesn't contain electron.
